In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
gender_label_encoder = LabelEncoder()
data['Gender'] = gender_label_encoder.fit_transform(data['Gender'])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [5]:
data.shape

(10000, 11)

In [6]:
data.value_counts('Exited')

Exited
0    7963
1    2037
Name: count, dtype: int64

In [7]:
from sklearn.preprocessing import OneHotEncoder

one_hot_encoder_geography = OneHotEncoder()
geography_encoded = one_hot_encoder_geography.fit_transform(data[['Geography']]).toarray()
geography_encoded

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [8]:
one_hot_encoder_geography.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [9]:
geo_encoded_df = pd.DataFrame(geography_encoded, columns = one_hot_encoder_geography.get_feature_names_out(['Geography']))
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

ERROR! Session/line number was not unique in database. History logging moved to new session 15

In [10]:
data = pd.concat([data.drop('Geography',axis=1), geo_encoded_df],axis=1)

In [11]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [12]:
import pickle

In [13]:
with open('label_encoder_gender_1.pkl','wb') as f:
    pickle.dump(gender_label_encoder,f)

with open('one_hot_encoder_geography_1.pkl','wb') as f:
    pickle.dump(one_hot_encoder_geography,f)

In [14]:
X = data.drop(['Exited'],axis=1)
y = data['Exited']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
X_train.shape

(8000, 12)

In [17]:
X_test.shape

(2000, 12)

In [18]:
from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()
X_train = standard_scaler.fit_transform(X_train)
X_test = standard_scaler.transform(X_test)

In [19]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [20]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [22]:
with open('scaler_1.pkl','wb') as f:
    pickle.dump(standard_scaler,f)

ANN IMPLEMENTATION

In [23]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

2026-03-20 19:23:34.274905: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-03-20 19:23:34.327281: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-03-20 19:23:34.327337: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-03-20 19:23:34.329042: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-03-20 19:23:34.337351: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-03-20 19:23:35.512669: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [24]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid'),
])

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [26]:
opt = tf.keras.optimizers.Adam(learning_rate=0.001)
loss = tf.keras.losses.BinaryCrossentropy()
loss

In [27]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [28]:
log_dir = 'logs/fit/' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [29]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [30]:
### Train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorboard_callback,early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 2s 4ms/step - loss: 0.4492 - accuracy: 0.8076 - val_loss: 0.4009 - val_accuracy: 0.8225
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3962 - accuracy: 0.8353 - val_loss: 0.3655 - val_accuracy: 0.8490
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3617 - accuracy: 0.8547 - val_loss: 0.3499 - val_accuracy: 0.8570
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3479 - accuracy: 0.8574 - val_loss: 0.3479 - val_accuracy: 0.8570
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3407 - accuracy: 0.8586 - val_loss: 0.3425 - val_accuracy: 0.8565
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3361 - accuracy: 0.8605 - val_loss: 0.3532 - val_accuracy: 0.8605
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3332 - accuracy: 0.8633 - val_loss: 0.3424 - val_accuracy: 0.8595
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3289 - accuracy: 0.8649 - val_loss: 0.3469 - val_accuracy: 0.8585
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3267 - accuracy: 0.8611 - val_loss: 0.3463 - val_accuracy: 0.8580
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3257 - accuracy: 0.8633 - val_loss: 0.3405 - val_accuracy: 0.8650
Epoch 11/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3243 - accuracy: 0.8640 - val_loss: 0.3441 - val_accuracy: 0.8600
Epoch 12/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3236 - accuracy: 0.8633 - val_loss: 0.3397 - val_accuracy: 0.8615
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3200 - accuracy: 0.8656 - val_loss: 0.3397 - val_accuracy: 0.8600
Epoch 14/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3195 - accuracy: 0.8652 - val_loss: 0.3407 - val_accuracy: 0.8630
Epoch 15/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3185 - accuracy: 0.8661 - val_loss: 0.3424 - val_accuracy: 0.8600
Epoch 16/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3158 - accuracy: 0.8664 - val_loss: 0.3426 - val_accuracy: 0.8625
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3151 - accuracy: 0.8681 - val_loss: 0.3392 - val_accuracy: 0.8625
Epoch 18/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3131 - accuracy: 0.8686 - val_loss: 0.3406 - val_accuracy: 0.8670
Epoch 19/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3122 - accuracy: 0.8691 - val_loss: 0.3421 - val_accuracy: 0.8605
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3098 - accuracy: 0.8704 - val_loss: 0.3547 - val_accuracy: 0.8570
Epoch 21/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3102 - accuracy: 0.8701 - val_loss: 0.3453 - val_accuracy: 0.8575
Epoch 22/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3083 - accuracy: 0.8698 - val_loss: 0.3401 - val_accuracy: 0.8605

In [31]:
model.save('model_1.h5')

/home/hemalatha.pallem/Desktop/genai/annclassification/venv/lib/python3.10/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [32]:
%load_ext tensorboard

In [33]:
%tensorboard --logdir logs/fit/